import { IProduct } from './Iproduct';

export const ProductList: IProduct[] = [
  {
    id: 1,
    Name: 'Pasta',
    Description: 'Hot Marconi And Salsa',
    Price: 200,
    img: '/assets/img/pasta.webp',
    Serving: 1,
  },
  {
    id: 2,
    Name: 'Hamburger',
    Description: 'Bread ,Meat, tomato,onion ,cheese',
    Price: 300,
    img: '/assets/img/ham.jpg',
    Serving: 5,
  },
  {
    id: 3,
    Name: 'Cheese Pizza',
    Description: ' Meat,tomato And cheese',
    Price: 250,
    img: '/assets/img/cheesePizza.jpg',
    Serving: 3,
  },
  {
    id: 4,
    Name: 'Chicken Wings',
    Description: ' chicken',
    Price: 150,
    img: '/assets/img/chicken.jpg',
    Serving: 1,
  },

  {
    id: 6,
    Name: 'Desert Curry',
    Description: ' chicken , Rice And potato',
    Price: 400,
    img: '/assets/img/3.jpg',
    Serving: 3,
  },
  {
    id: 7,
    Name: 'Ice Cream',
    Description: ' chocolate , vanilla, biscuits',
    Price: 10,
    img: '/assets/img/icecream.jpg',
    Serving: 1,
  },
  {
    id: 8,
    Name: 'Ice Cream Pancake',
    Description: ' chocolate , ice cream, biscuits',
    Price: 30,
    img: '/assets/img/desert.jpg',
    Serving: 1,
  },
  {
    id: 9,
    Name: 'Cheesecake',
    Description: ' chocolate , Cake',
    Price: 50,
    img: '/assets/img/cake.jpg',
    Serving: 1,
  },
  {
    id: 1,
    Name: 'Pasta',
    Description: 'Hot Marconi And Salsa',
    Price: 200,
    img: '/assets/img/pasta.webp',
    Serving: 1,
  },
  {
    id: 2,
    Name: 'Hamburger',
    Description: 'Bread ,Meat, tomato,onion ,cheese',
    Price: 300,
    img: '/assets/img/ham.jpg',
    Serving: 5,
  },
  {
    id: 3,
    Name: 'Cheese Pizza',
    Description: ' Meat,tomato And cheese',
    Price: 250,
    img: '/assets/img/cheesePizza.jpg',
    Serving: 3,
  },
  {
    id: 4,
    Name: 'Chicken Wings',
    Description: ' chicken',
    Price: 150,
    img: '/assets/img/chicken.jpg',
    Serving: 1,
  },
];
